
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile  # Asegúrate de que el nombre sea correcto
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - ./app:/app      # Monta la carpeta de la aplicación para persistencia de archivos
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
 
